### ISSUE TITLE
Request for HTML template for the TODO items

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#211]
Hi,

I am completely illiterate with HTML, and I am wondering if there is a certain HTML template that I may use to properly display the following structure written in Vimwiki?

```
* [.] TODO level 1: project
    * [ ] TODO level 2: subproject 1
    * [o] TODO level 2: subproject 2
        * [ ] TODO level 3 ...
        * [X] TODO level 3 ...
```

Thank you!

All the best, 

-Linfeng

REF: to specify a HTML template --- http://www.rosipov.com/blog/custom-templates-in-vimwiki/

**Comment by EinfachToll** [comment]
I don't really understand what you want to know. If you want to know how to write this structure in HTML, well, then put it in your wiki, convert it and take a look at the output.
If you want to highlight the `TODO`, you can use a custom CSS.
Not sure what you want to use the template functionality for.
Let me know what exactly you want to achieve.

**Comment by llinfeng** [comment]
Ah,

Thanks for pointing out the way to highlight;

However, I am looking for some "graphical conversion" of the bulletin structure given in my sample. To be more precise, I would expect some like:
* An empty square box for `* [ ]`
* A square box with small circle in the middle for ` * [o]`
* A square box with dot in the middle for `* [.]`
* A crossed out box for `* [X]` (or the whole line in "strike out" form)

Basically, I am looking for some more vivid display/conversion of the TODO list that has been beautifully rendered in by Vimwiki in Vim. By default, the sample structure is displayed as follows in HTML (or via browser)
![sample-todo-list-vimwiki](https://cloud.githubusercontent.com/assets/5890407/15542602/7db7776c-225f-11e6-94bf-a21fd7061046.png)

Is this getting clearer?

Thanks again!

All the best, 

-Linfeng

**Comment by EinfachToll** [comment]
Ok, now I know what you want. But Vimwiki already provides a CSS file which renders that a bit more nicely, including checkboxes. This CSS file must be in the directory where your HTML files are, so that your browser finds it. It is normally copied into the HTML output directory when converting. Do you see a file `style.css` there? Is it there if you run `:VimwikiAll2HTML` again? There was a bug until some weeks ago where the CSS file was only copied with `:VimwikiAll2HTML`, not `:Vimwiki2HTML`.

**Comment by llinfeng** [comment]
Yes, this exactly what I was looking for!

I was unaware of the command `:VimwikiAll2HTML`. I have remapped this command to the key-bindings `<Leader>whh`, which is currently mapped to `:Vimwiki2HTMLBrowse`.

```
" Use <Leader>whh to both update the *.wiki and copy/overwrite `style.css`
nmap <leader>whh :VimwikiAll2HTML<CR>
```

Thank you!

All the best, 

-Linfeng

**Comment by llinfeng** [comment]
Oh, by the way, which lines in the `style.css` file that stipulate the rendering of "checkboxes"? Just curious. @EinfachToll  Thanks a lot! [I am thinking about getting `@` rendered with more empahsis.]

**Comment by EinfachToll** [comment]
It's the part `.done0` up to `.done4`. For example, the rule
```css
.done0 {
    /* list-style: none; */
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAxQAAAMUBHc26qAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAA7SURBVCiR7dMxEgAgCANBI3yVRzF5KxNbW6wsuH7LQ2YKQK1mkswBVERYF5Os3UV3gwd/jF2SkXy66gAZkxS6BniubAAAAABJRU5ErkJggg==);
    background-repeat: no-repeat;
    background-position: 0 .2em;
    padding-left: 1.5em;
}
```
sets certain properties for every HTML element which has the class `done0`. (The HTML converter makes sure that all `<li>` elements for unchecked list items have this class, so they become `<li class="done0">` in the HTML output).
These properties define a background image for the list item (which is not really displayed in the background) and make sure everything is neatly arranged.
The strange long string is actually a PNG image of an empty checkbox, encoded with base64.
